package it.polimi.ingsw.model;

public enum States {
    BEFORE, LOBBY, SELECTWINDOW, SELECTDRAFT, SELECTCARD, ERROR, SELECTMOVE1, PUTDICEINWINDOW, SELECTMOVE2, USETOOLCARD, USETOOLCARD2, USETOOLCARD3, ENDROUND, SCORECALCULATION, ENDMATCH;
}
