package it.polimi.ingsw.model;

public enum States {
    LOBBY, SELECTWINDOW, SELECTDRAFT, SELECTCARD, ERROR, SELECTMOVE1, PUTDICEINWINDOW, SELECTMOVE2, USETOOLCARD, USETOOLCARD2, USETOOLCARD3, USETOOLCARD4, ENDROUND, ENDMATCH;
}
